defaults: &defaults
  fog:
    s3:
      provider: "AWS"
      aws_access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
      aws_secret_access_key: <%= ENV['S3_AWS_SECRET_ACCESS_KEY'] %>
      region: <%= ENV['S3_REGION'] %>
      directory: <%= ENV['S3_BUCKET'] %>

development:
  fog:
    s3:
      provider: "AWS"
      aws_access_key_id: AKIAIPDC44JXGOMU2RBQ
      aws_secret_access_key: 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
      region: us-east-1
      directory: actionsimages
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
